### ISSUE TITLE
Unhandled exception error

### ISSUE THREAD

**Issue by Silther** [BookFusion/calibre-plugin#2]
calibre, version 6.15.1
FEHLER: Unbehandelter Ausnahmefehler: <b>RuntimeError</b>:wrapped C/C++ object of type QNetworkReply has been deleted

calibre 6.15.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Action Chains (1, 18, 5) && BookFusion Plugin (0, 8, 0) && Count Pages (1, 13, 0) && Job Spy (1, 0, 228) && KOReader Sync (0, 4, 1) && Kindle hi-res covers (0, 5, 0) && Last Modified (0, 8, 4) && PocketBook632 (1, 0, 2) && Quality Check (1, 13, 4) && Resize Cover (1, 2, 0)
Traceback (most recent call last):
  File "calibre_plugins.bookfusion.upload_worker", line 89, in complete_check
RuntimeError: wrapped C/C++ object of type QNetworkReply has been deleted

![image](https://user-images.githubusercontent.com/97352673/231458732-bec78df6-c97b-451f-ab13-f156937a291d.png)

**Comment by skillachie** [comment]
Thanks for reporting @xIUPITERx   . We have added it to our backlog and will take a look this month. Does this prevent your ebook from syncing? Or does it sync when you try a second time?

**Comment by Silther** [comment]
The syncing works fine, but I have to restart calibre after it to use it again as I can't get rid of the error message.

**Comment by skillachie** [comment]
> The syncing works fine, but I have to restart calibre after it to use it again as I can't get rid of the error message.

Got it.

**Comment by skillachie** [comment]
@xIUPITERx   You can download [BookFusion.zip](https://github.com/BookFusion/calibre-plugin/releases/download/v0.8.1/BookFusion.zip)

We will also be pushing it to Calibre today.
